### ISSUE TITLE
Chrome Extension entfernt alle Link Unterstreichungen

### ISSUE THREAD

**Issue by pke** [getcahoots/extension#54]
Wenn man die Extension installiert wird unter Chome ein "injected stylesheet" mit folgendem Inhalt on jede Seite eingefügt, und zwar unabhängig davon ob cahoots läuft oder nicht. Es muss nur geladen sein.

```css
a:-webkit-any-link {
  text-decoration: none;
}
```
![image](https://user-images.githubusercontent.com/164625/79247966-7eb3a100-7e7b-11ea-8915-4edf3c1cb6d9.png)

Ich finde aber nichts im Sourcecode was das provozieren könnte?
